language: python
matrix:
  include:
  - os: linux
    python: 2.7
    env: BUILD=PYPI
  - os: linux
    python: 3.7
  - os: linux
    python: 3.5
  - os: linux
    sudo: required
    python: 3.6
    env: BUILD=LINUX
before_install:
- "./.travis/before_install.sh"
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install pyinstaller
script:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 setup.py flake8; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then python setup.py flake8; fi
- nose2 --with-coverage --coverage apsconnectcli/ --coverage-report xml
after_success:
- "./.travis/after_success.sh"
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: szhuFeOjchPI0E6lEsn2BbggPP22G2vOv6nOnlDY6qtRr8dDRO2BOyTBWKcC1fOK+xofAp7mFo564RqQAASCWrXdrnI9b76t1ntLl5D89LTn4b+zSnDvDrDuet92aoi1BGLH/OyWKIMHkEavm0EAyqcreS0BNC62JN9Xr7ciEiXYLTknmaYg1y4ltg5cVfvKJArgDsxQqdcIrhaGjnLZ5rDDgegfyzoWgiezzCVt4/OhWVm7La9J6uVtAjheWTKDz+mmSslh0/ESYwFciHgdtdfEme+JyGJQ5VlrP+2BhKuHMqrSaJubYfGwi5ATklFZogAq+H2G81qksM6VmCQBT6TjqGBIhCjbpl5bUxZsM/oZ5PQmZ5k+N6DHXce/6z1j68fm/0kgQwpSa10Q65QtFjDnd2YY0/WRGKnvG9tz6DqIqQTeDEvqzpmZeGwG75/5lErumfTLX5ocRMXd7RjonG7LK7SQEQXvrmb7aSL2EpGnzWTfrcqbVwSBiYU+eNViOVmKC/56zEKS/FP98bXnCbFXff8anVVThvgcYjiNiypDf1B1o+7Hpso5sbrZVyjbtHTzcULhYTn39k/BEqDopSFPvUISyMNuEoOFV9uaYv4horMynJhDvnQmNkDnWs5uc7WDhFjpp2gVP/Mvj3Z/1y4KA/D3hWJx8b81sCiYxnQ=
    file: dist/apsconnect-mac
    on:
      tags: true
      all_branches: true
      repo: ingrammicro/apsconnect-cli
      condition: "$BUILD = OSX"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: szhuFeOjchPI0E6lEsn2BbggPP22G2vOv6nOnlDY6qtRr8dDRO2BOyTBWKcC1fOK+xofAp7mFo564RqQAASCWrXdrnI9b76t1ntLl5D89LTn4b+zSnDvDrDuet92aoi1BGLH/OyWKIMHkEavm0EAyqcreS0BNC62JN9Xr7ciEiXYLTknmaYg1y4ltg5cVfvKJArgDsxQqdcIrhaGjnLZ5rDDgegfyzoWgiezzCVt4/OhWVm7La9J6uVtAjheWTKDz+mmSslh0/ESYwFciHgdtdfEme+JyGJQ5VlrP+2BhKuHMqrSaJubYfGwi5ATklFZogAq+H2G81qksM6VmCQBT6TjqGBIhCjbpl5bUxZsM/oZ5PQmZ5k+N6DHXce/6z1j68fm/0kgQwpSa10Q65QtFjDnd2YY0/WRGKnvG9tz6DqIqQTeDEvqzpmZeGwG75/5lErumfTLX5ocRMXd7RjonG7LK7SQEQXvrmb7aSL2EpGnzWTfrcqbVwSBiYU+eNViOVmKC/56zEKS/FP98bXnCbFXff8anVVThvgcYjiNiypDf1B1o+7Hpso5sbrZVyjbtHTzcULhYTn39k/BEqDopSFPvUISyMNuEoOFV9uaYv4horMynJhDvnQmNkDnWs5uc7WDhFjpp2gVP/Mvj3Z/1y4KA/D3hWJx8b81sCiYxnQ=
    file:
      - dist/apsconnect-lin
      - dist/apsconnect.exe
    on:
      tags: true
      all_branches: true
      repo: ingrammicro/apsconnect-cli
      condition: "$BUILD = LINUX"
  - provider: pypi
    user: "__token__"
    password:
      secure: pypi-AgEIcHlwaS5vcmcCJDJkNTA1YjE4LWQzZGQtNDkyYy1hY2NmLTFmZDlhNjFhZjlmNwACPnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJhcHNjb25uZWN0Y2xpIl19LCAidmVyc2lvbiI6IDF9AAAGIEyaTWtxWpqFiDXOnzKi8Xr7R6KJkojLtcWcrf_Bcbxs
    on:
      tags: true
      all_branches: true
      distributions: sdist bdist_wheel
      repo: ingrammicro/apsconnect-cli
      condition: "$BUILD = PYPI"
